dependent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('persons/', include('persons.urls')),
    path('', include('sajib.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

persons/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.person_create_view, name='person_add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
]

sajib/urls.py
from django.urls import path
from .views import Index, load_district

urlpatterns = [
    path('', Index, name='index'),
    path('load-district', load_district, name='load-district'),
]

persons/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=124)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

sajib/models.py
from django.db import models

class Division(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    

class District(models.Model):
    division = models.ForeignKey(Division, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Upazila(models.Model):
    division = models.ForeignKey(Division, on_delete=models.CASCADE, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Person(models.Model):
    full_Name = models.CharField(max_length=45)
    division = models.ForeignKey(Division, on_delete=models.SET_NULL, blank=True, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    upazila = models.ForeignKey(Upazila, on_delete=models.SET_NULL, blank=True, null=True)
    gender_choice = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others')
    )
    gender = models.CharField(choices=gender_choice, max_length=10)
    email = models.EmailField(max_length=255, unique=True)
    mobile_No = models.CharField(max_length=11, unique=True)
    date_of_Birth = models.DateField()
    university_choice = (
        ('Bangladesh Agricultural University', 'Bangladesh Agricultural University'),
        ('Hajee Mohammad Danesh Science and Technology University', 'Hajee Mohammad Danesh Science and Technology University'),
        ('Khulna University', 'Khulna University'),
        ('Noakhali Science and Technology University', 'Noakhali Science and Technology University'),
        ('Patuakhali Science & Technology University', 'Patuakhali Science & Technology University'),
        ('University of Rajshahi', 'University of Rajshahi'),
        ('Sher-e-Bangla Agricultural University', 'Sher-e-Bangla Agricultural University'),
        ('Sylhet Agricultural University', 'Sylhet Agricultural University'),
        ('Others', 'Others'),
    )
    university_Name = models.CharField(choices=university_choice, max_length=100)
    picture = models.ImageField(upload_to='images/', blank=True)

    
    def __str__(self):
        return self.full_Name

persons/forms.py
from django import forms

from persons.models import Person, City


class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

sajib/forms.py
from .models import Person, District, Division, Upazila
from django.forms import ModelForm
    

class PersonForm(ModelForm):
    
    class Meta:
        model = Person
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['district'].queryset = models.District.objects.none()

            if 'district' in self.data:
                try:
                    division_id = int(self.data.get('division'))
                    self.fields['district'].queryset = models.District.objects.filter(division_id=division_id).order_by('name')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                self.fields['district'].queryset = self.instance.division.district_set.order_by('name')

            self.fields['upazila'].queryset = models.Upazila.objects.none()

            if 'upazila' in self.data:
                try:
                    district_id = int(self.data.get('district'))
                    self.fields['upazila'].queryset = models.Upazila.objects.filter(district_id=district_id).order_by('name')
                except (ValueError, TypeError):
                    pass
            elif self.instance.pk:
                self.fields['upazila'].queryset = self.instance.district.upazila_set.order_by('name')

persons/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PersonCreationForm
from .models import Person, City


def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person_add')
    return render(request, 'persons/home.html', {'form': form})


def person_update_view(request, pk):
    person = get_object_or_404(Person, pk=pk)
    form = PersonCreationForm(instance=person)
    if request.method == 'POST':
        form = PersonCreationForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'persons/home.html', {'form': form})


# AJAX
def load_cities(request):
    country_id = request.GET.get('country_id')
    cities = City.objects.filter(country_id=country_id).all()
    return render(request, 'persons/city_dropdown_list_options.html', {'cities': cities})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

sajib/views.py
from django.shortcuts import render
from .models import Person, District, Division, Upazila
from .forms import PersonForm

# Create your views here.
def load_district(request):
    division_id = request.GET.get('division')
    district = District.objects.filter(division_id=division_id).order_by('name')

    district_id = request.GET.get('district')
    upazila = Upazila.objects.filter(district_id=district_id).order_by('name')
    context = {
        'district': district,
        'upazila': upazila
    }
    return render(request, 'sajib/district_dropdown_list_options.html', context)
def Index(request):
    form = PersonForm

    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            form.save()

    context = {
         'form': form
     }
    return render(request, 'sajib/index.html', context)

templates/persons/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/persons/home.html
<!doctype html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Dependent Dropdown in Django</title>
</head>
<body>
<h2>Person Form</h2>

<form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/sajib/district_dropdown_list_options.html
  
<option value="">---------</option>
{% for district in district %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}
{% for upazila in upazila %}
<option value="{{ upazila.pk }}">{{ upazila.name }}</option>
{% endfor %}

templates/sajib/index.html
  
<!doctype html>
{% load crispy_forms_tags %}
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    
    <h2 class="text-center">Dependent DropDown List Not Working Properly</h2>
    <div class="container">
      <form action="" method="post" enctype="multipart/form-data" id="RegistrationForm" data-district-url={% url 'load-district' %}>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit data</button>
      </form>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
      $("#id_division").change(function () {
        var url = $("#RegistrationForm").attr("data-district-url");
        var divisionId = $(this).val();

        $.ajax({
          url: url,
          data: {
            'division': divisionId
          },
          success: function (data) {
            $("#id_district").html(data);
          }
        });

      });
      $("#id_district").change(function () {
        var url = $("#TeacherRegistrationForm").attr("data-upazilla-url");
        var districtId = $(this).val();

        $.ajax({
          url: url,
          data: {
            'district': districtId
          },
          success: function (data) {
            $("#id_upazila").html(data);
          }
        });

      });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>